import type { CSSProperties, ReactElement, ReactNode } from 'react'

import { cn } from '@oztix/roadie-core/utils'

import type { BadgeProps } from '../Badge'
import {
  NavigatorDestination,
  type NavigatorDestinationProps
} from './NavigatorDestination'
import { badgeDot, presentNavIcon } from './presentNavIcon'
import { initialOf } from './splitSecondary'
import {
  navigatorTabIconFrameVariants,
  navigatorTabInitialClass,
  navigatorTabVariants
} from './variants'

/** When the bar is collapsed, which edge this tab floats to as a circle. */
export type NavigatorTabCircleSide = 'start' | 'end'

export type NavigatorTabProps = Omit<
  NavigatorDestinationProps,
  | 'href'
  | 'circleSide'
  | 'style'
  | 'ariaCurrent'
  | 'dataCurrent'
  | 'className'
  | 'children'
> & {
  label: ReactNode
  icon?: ReactNode
  /** Shown as a corner dot in every presentation. */
  badge?: ReactElement<BadgeProps>
  /** Same smart-href contract as `Navigator.Item`. Omit for a `<button>`. */
  href?: string
  active?: boolean
  /** Announced through `aria-current`; defaults to `active`, which only drives the pill. */
  current?: boolean
  /** False when active through a sub-page, so it announces the section, not the page. */
  isPage?: boolean
  /** The bar is collapsed on scroll — drives the edge-circle presentation. */
  collapsed?: boolean
  /** When collapsed, the edge this tab floats to; omitted, it shrinks away but stays in the AT tree. */
  circleSide?: NavigatorTabCircleSide
  /** The track column, which a collapsed circle travels from. */
  index: number
  /** The trailing circle outside the track; collapsed, it shrinks to the edge circles' size. */
  pinned?: boolean
}

/** A bar destination generated by `Navigator.Primary`, never authored. */
export function NavigatorTab({
  label,
  icon,
  badge,
  href,
  active = false,
  current = active,
  isPage = true,
  collapsed = false,
  circleSide,
  pinned = false,
  index,
  ...rest
}: NavigatorTabProps) {
  const presentation = pinned
    ? 'pinned'
    : !collapsed
      ? 'expanded'
      : circleSide
        ? 'circle'
        : 'hidden'
  const content = (
    <>
      <span data-slot='navigator-tab-label' className='sr-only'>
        {label}
      </span>
      {badge ? ' ' : null}
      <span
        data-slot='navigator-tab-icon-frame'
        className={navigatorTabIconFrameVariants({
          counterScaled: pinned && collapsed
        })}
      >
        {/* A CSS animation, so re-tapping an already-active tab doesn't re-bounce. */}
        {icon ? (
          presentNavIcon(
            icon,
            cn('size-7', active && 'animate-pop-tap'),
            'navigator-tab-icon'
          )
        ) : (
          <span
            aria-hidden
            data-slot='navigator-tab-initial'
            className={cn(
              navigatorTabInitialClass,
              active && 'animate-pop-tap'
            )}
          >
            {initialOf(label)}
          </span>
        )}
        {badge ? badgeDot(badge) : null}
      </span>
    </>
  )

  const finalClassName = navigatorTabVariants({
    active,
    presentation,
    circleSide,
    collapsed
  })
  // Only the page itself claims 'page'; a disclosure or section claims 'true'.
  const isDisclosure = rest['aria-expanded'] !== undefined
  const ariaCurrent = current
    ? isPage && !isDisclosure
      ? 'page'
      : 'true'
    : undefined

  return (
    <NavigatorDestination
      {...rest}
      href={href}
      circleSide={presentation === 'circle' ? circleSide : undefined}
      style={{ '--navigator-primary-index': String(index) } as CSSProperties}
      ariaCurrent={ariaCurrent}
      dataCurrent={active}
      className={finalClassName}
    >
      {content}
    </NavigatorDestination>
  )
}

NavigatorTab.displayName = 'NavigatorTab'
