import type { CSSProperties, MouseEvent, ReactNode } from 'react'

import { cn } from '@oztix/roadie-core/utils'

import { NavigatorDestination } from './NavigatorDestination'
import { presentNavIcon } from './presentNavIcon'
import { navigatorTabVariants } from './variants'

/** When the bar is collapsed, which edge this tab floats to as a circle. */
export type NavigatorTabCircleSide = 'left' | 'right'

export type NavigatorTabProps = {
  label: ReactNode
  icon?: ReactNode
  /** Same smart-href contract as `Navigator.Item`. Omit for a `<button>`. */
  href?: string
  active?: boolean
  /** The bar is collapsed on scroll — drives the edge-circle presentation. */
  collapsed?: boolean
  /**
   * When collapsed, float this tab as a circle on the given edge. Omitted
   * while collapsed means the tab scales to nothing but keeps its grid
   * column and stays in the AT tree, so a screen-reader user keeps the full
   * destination set.
   */
  circleSide?: NavigatorTabCircleSide
  /**
   * Which column of the bar's track this tab occupies. A collapsed circle
   * translates to the edge from its own column, so the travel needs it.
   */
  index: number
  /** Set only on the generated final tab, which discloses a pane. */
  expanded?: boolean
  /** Id of the pane this tab discloses. Only meaningful while `expanded`. */
  controls?: string
  className?: string
  onSelect?: (event: MouseEvent) => void
}

/**
 * A tab-bar destination. Generated by `Navigator.Primary` from the declared
 * tree, never authored — which is why it is not part of the compound.
 */
export function NavigatorTab({
  label,
  icon,
  href,
  active = false,
  collapsed = false,
  circleSide,
  index,
  expanded,
  controls,
  className,
  onSelect
}: NavigatorTabProps) {
  const presentation = !collapsed
    ? 'expanded'
    : circleSide
      ? 'circle'
      : 'hidden'
  const content = (
    <>
      {/* size-7 icon in both presentations — the collapsed circle grows to
          size-14 to keep the lg-IconButton padding ratio rather than shrinking
          the icon. The bounce is a CSS animation, so it fires only as the tab
          starts matching `active` — re-tapping an already-active tab does not
          re-bounce, matching iOS scroll-to-top instead (Pane.Header's compact
          title already does that). */}
      {presentNavIcon(
        icon,
        active,
        cn('size-7', active && 'animate-pop-tap'),
        'navigator-tab-icon'
      )}
      <span
        className={
          presentation === 'circle' ? 'sr-only' : 'max-w-full truncate'
        }
      >
        {label}
      </span>
    </>
  )

  const finalClassName = cn(
    navigatorTabVariants({ active, presentation, circleSide }),
    className
  )
  // A disclosure button doesn't navigate to a page — it reveals a set that
  // may contain the active one, so it claims 'true' currency, not 'page'.
  const isDisclosure = expanded !== undefined
  const ariaCurrent = active ? (isDisclosure ? 'true' : 'page') : undefined

  return (
    <NavigatorDestination
      href={href}
      circleSide={presentation === 'circle' ? circleSide : undefined}
      style={{ '--navigator-tab-index': String(index) } as CSSProperties}
      ariaCurrent={ariaCurrent}
      dataCurrent={active}
      expanded={expanded}
      controls={controls}
      className={finalClassName}
      onClick={onSelect}
    >
      {content}
    </NavigatorDestination>
  )
}

NavigatorTab.displayName = 'NavigatorTab'
