import type { CSSProperties, MouseEvent, ReactNode } from 'react'

import { cn } from '@oztix/roadie-core/utils'

import {
  NavigatorDestination,
  type NavigatorDestinationProps
} from './NavigatorDestination'
import { presentNavIcon } from './presentNavIcon'
import { navigatorTabVariants } from './variants'

/** When the bar is collapsed, which edge this tab floats to as a circle. */
export type NavigatorTabCircleSide = 'left' | 'right'

export type NavigatorTabProps = Omit<
  NavigatorDestinationProps,
  | 'href'
  | 'circleSide'
  | 'style'
  | 'ariaCurrent'
  | 'dataCurrent'
  | 'expanded'
  | 'controls'
  | 'className'
  | 'children'
  | 'onSelect'
> & {
  label: ReactNode
  icon?: ReactNode
  /** Same smart-href contract as `Navigator.Item`. Omit for a `<button>`. */
  href?: string
  active?: boolean
  /** Announced through `aria-current`; defaults to `active`, which only drives the pill. */
  current?: boolean
  /** False when active through a sub-page, so it announces the section, not the page. */
  isPage?: boolean
  /** The bar is collapsed on scroll — drives the edge-circle presentation. */
  collapsed?: boolean
  /** When collapsed, the edge this tab floats to; omitted, it shrinks away but stays in the AT tree. */
  circleSide?: NavigatorTabCircleSide
  /** The track column, which a collapsed circle travels from. */
  index: number
  /** The trailing circle outside the track; it never collapses. */
  pinned?: boolean
  /** Set only on the generated final tab, which discloses a pane. */
  expanded?: boolean
  /** Id of the pane this tab discloses. Only meaningful while `expanded`. */
  controls?: string
  className?: string
  onSelect?: (event: MouseEvent) => void
}

/** A bar destination generated by `Navigator.Primary`, never authored. */
export function NavigatorTab({
  label,
  icon,
  href,
  active = false,
  current = active,
  isPage = true,
  collapsed = false,
  circleSide,
  pinned = false,
  index,
  expanded,
  controls,
  className,
  onSelect,
  onClick,
  ...rest
}: NavigatorTabProps) {
  const presentation = pinned
    ? 'pinned'
    : !collapsed
      ? 'expanded'
      : circleSide
        ? 'circle'
        : 'hidden'
  const content = (
    <>
      {/* A CSS animation, so re-tapping an already-active tab doesn't re-bounce. */}
      {presentNavIcon(
        icon,
        active,
        cn('size-7', active && 'animate-pop-tap'),
        'navigator-tab-icon'
      )}
      <span
        className={
          presentation === 'circle' || presentation === 'pinned'
            ? 'sr-only'
            : 'max-w-full truncate'
        }
      >
        {label}
      </span>
    </>
  )

  const finalClassName = cn(
    navigatorTabVariants({ active, presentation, circleSide }),
    className
  )
  // Only the page itself claims 'page'; a disclosure or section claims 'true'.
  const isDisclosure = expanded !== undefined
  const ariaCurrent = current
    ? isPage && !isDisclosure
      ? 'page'
      : 'true'
    : undefined

  return (
    <NavigatorDestination
      {...rest}
      href={href}
      circleSide={presentation === 'circle' ? circleSide : undefined}
      style={{ '--navigator-primary-index': String(index) } as CSSProperties}
      ariaCurrent={ariaCurrent}
      dataCurrent={active}
      expanded={expanded}
      controls={controls}
      className={finalClassName}
      onClick={onSelect ?? onClick}
    >
      {content}
    </NavigatorDestination>
  )
}

NavigatorTab.displayName = 'NavigatorTab'
