/**
 * What each docs component a page imports from `@/` becomes in the page's
 * markdown twin, keyed by the name the page uses. `scripts/llms.ts` fails the
 * build on a component missing here, including one passed as a prop.
 * - `rendered`: a renderer in `scripts/twin-renderers.ts` writes its data
 * - `drawing`: it only draws for the site; the sentence before it says what it shows
 * - `pending`: data still waiting for a renderer; this only shrinks
 */
export const TWIN_COMPONENTS = {
  AccentScales: 'rendered',
  BreakpointScale: 'rendered',
  CardAnatomyExample: 'drawing',
  CardSizes: 'rendered',
  CardStateExample: 'drawing',
  CardMenu: 'drawing',
  CartContentsParityDemo: 'drawing',
  CartDrawerParityDemo: 'drawing',
  CartExpiryDialogsDemo: 'drawing',
  CatalogueIndex: 'rendered',
  ChartLabelLimits: 'rendered',
  ComparisonTable: 'rendered',
  ComponentReads: 'rendered',
  ContainerScale: 'rendered',
  CopyLimits: 'rendered',
  DataFormatReads: 'rendered',
  DatavizSwatches: 'rendered',
  DateStyleScale: 'rendered',
  DisplayStyles: 'drawing',
  FocusRingList: 'rendered',
  FormExamples: 'drawing',
  IconSizeScale: 'rendered',
  IllustrationGallery: 'rendered',
  IntentEmphasis: 'drawing',
  LayeringScale: 'rendered',
  MachineValueReads: 'rendered',
  ModelDiagram: 'drawing',
  MomentReads: 'rendered',
  PaletteExample: 'drawing',
  PeriodComparisons: 'rendered',
  PhraseTable: 'rendered',
  QuerySuggestions: 'rendered',
  RadiusScale: 'rendered',
  RangeTable: 'rendered',
  ReadingAidsChart: 'drawing',
  RelativeLadder: 'rendered',
  RhythmTable: 'rendered',
  RimLightScale: 'drawing',
  RowDiagram: 'drawing',
  RowsThatFill: 'drawing',
  ScaleSwatches: 'rendered',
  ShadowScale: 'drawing',
  SpacingScale: 'rendered',
  Stage: 'drawing',
  TimeStyleScale: 'rendered',
  TransitionList: 'rendered',
  TypeScale: 'rendered',
  UpcomingShows: 'drawing',
  ViewMeilisearch: 'rendered',
  ViewSearchParams: 'rendered',
  ZoneTable: 'rendered'
} satisfies Record<string, 'rendered' | 'drawing' | 'pending'>
