name: Setup
description: Sets up Node.js, pnpm, Turbo cache, and installs dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache Turbo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Cache TypeScript build info
      uses: actions/cache@v4
      with:
        path: |
          **/*.tsbuildinfo
        key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('**/tsconfig*.json', '**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-tsbuildinfo-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
